version: '3.8'

services:
  nest-app:
    build: .
    container_name: elastic-nest-backend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
